services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ~/.aws:/root/.aws:ro
    networks:
      - app-network
    command: ["python", "hybrid_main.py"]
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MCP server in stdio mode (for MCP clients)
  mcp-server:
    build: ./backend
    env_file:
      - .env
    volumes:
      - ~/.aws:/root/.aws:ro
    networks:
      - app-network
    command: ["python", "hybrid_main.py", "--mcp"]
    stdin_open: true
    tty: true

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
