services:
  # FastAPI Backend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DEPLOYMENT_ENV=${DEPLOYMENT_ENV:-local}
      - HOST_IP=${HOST_IP:-localhost}
      - PUBLIC_IP=${PUBLIC_IP:-localhost}
      - DEBUG=${DEBUG:-true}
      - ENVIRONMENT=${ENVIRONMENT:-development}
    volumes:
      - ./backend:/app
      - ./config:/app/config
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # React Landing Page
  frontend:
    build: 
      context: ./react-frontend
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8000/api/v1}
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL:-http://localhost:8000}
        - REACT_APP_AI_CHAT_URL=${REACT_APP_AI_CHAT_URL:-http://localhost:8501}
        - REACT_APP_DOCUMENT_ANALYSIS_URL=${REACT_APP_DOCUMENT_ANALYSIS_URL:-http://localhost:8502}
        - REACT_APP_WEB_SEARCH_URL=${REACT_APP_WEB_SEARCH_URL:-http://localhost:8503}
    ports:
      - "3000:80"
    volumes:
      - ./react-frontend/src:/app/src
      - ./config:/app/config
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8000/api/v1}
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL:-http://localhost:8000}
      - REACT_APP_AI_CHAT_URL=${REACT_APP_AI_CHAT_URL:-http://localhost:8501}
      - REACT_APP_DOCUMENT_ANALYSIS_URL=${REACT_APP_DOCUMENT_ANALYSIS_URL:-http://localhost:8502}
      - REACT_APP_WEB_SEARCH_URL=${REACT_APP_WEB_SEARCH_URL:-http://localhost:8503}
      - DEPLOYMENT_ENV=${DEPLOYMENT_ENV:-local}
      - HOST_IP=${HOST_IP:-localhost}
      - PUBLIC_IP=${PUBLIC_IP:-localhost}
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # AI Chat Streamlit App
  ai-chat:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - API_BASE_URL=http://backend:8000
      - DEPLOYMENT_ENV=${DEPLOYMENT_ENV:-local}
      - HOST_IP=${HOST_IP:-localhost}
      - PUBLIC_IP=${PUBLIC_IP:-localhost}
    volumes:
      - ./apps:/app
    command: streamlit run ai_chat.py --server.port=8501 --server.address=0.0.0.0 --server.headless=true
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Document Analysis Streamlit App
  document-analysis:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8502:8502"
    environment:
      - STREAMLIT_SERVER_PORT=8502
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - API_BASE_URL=http://backend:8000
      - DEPLOYMENT_ENV=${DEPLOYMENT_ENV:-local}
      - HOST_IP=${HOST_IP:-localhost}
      - PUBLIC_IP=${PUBLIC_IP:-localhost}
    volumes:
      - ./apps:/app
    command: streamlit run document_analysis.py --server.port=8502 --server.address=0.0.0.0 --server.headless=true
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8502/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Web Search Streamlit App
  web-search:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8503:8503"
    environment:
      - STREAMLIT_SERVER_PORT=8503
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - API_BASE_URL=http://backend:8000
      - DEPLOYMENT_ENV=${DEPLOYMENT_ENV:-local}
      - HOST_IP=${HOST_IP:-localhost}
      - PUBLIC_IP=${PUBLIC_IP:-localhost}
    volumes:
      - ./apps:/app
    command: streamlit run web_search.py --server.port=8503 --server.address=0.0.0.0 --server.headless=true
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8503/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge
